comparisonColumns:
- kind: column_family
  name: Test
- id
- region
- score
keyColumns:
- kind: column
  name: id
- kind: column
  name: name
aggregationColumns:
- kind: column
  name: status
- kind: column
  name: region
filters: []
targetColumns: []
nestedAggregationEnabled: false
comparisonSections:
- id: cs-1
  name: TBBBB
  columns:
  - kind: column
    name: region
  - kind: column
    name: status
- id: cs-2
  name: asdfadf
  columns:
  - kind: column
    name: name
  - kind: column
    name: status
_version: 3
