version: 1
next_index: 79
rules:
- rule_id: R056
  name: Valid status
  description: ''
  logic:
    format: value_vs_column
    column_name: status
    operator: eq
    target_value: active
    comparison_mode: comparison_vs_baseline
  extra_columns: []
- rule_id: R057
  name: Low Score
  description: ''
  logic:
    format: value_vs_column
    column_name: score
    operator: gt
    target_value: '90'
    target_values:
    - '90'
    comparison_mode: comparison_vs_baseline
  extra_columns: []
